package m.tech.jetbinance.ui.theme

import androidx.compose.ui.graphics.Color

object JetColor {
    val surface = Color(0xFF1F2630)
    val surfaceVariant = Color(0xFF2A303C)
    val onSurface = Color(0xFF858E9d)
    val onSurfaceVariant = Color(0xFF717A8B)
    val onSurfaceSecond = Color(0xFF424D5B)
    val text_primary = Color(0xFFEBECF0)
    val text_primary_inverse = Color(0xFF000000)
    val accent = Color(0xFFF7CD2E)
    val accentVariant = Color(0xFF2EBD85)
    val accentVariantTest = Color(0x802EBD85)
    val error = Color(0xFFF6465D)
    val errorTest = Color(0x80F6465D)
    val ripple = Color(0x80424D5B)
    val transparent = Color(0x00000000)
}

val md_theme_light_primary = Color(0xFF895100)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCBC)
val md_theme_light_onPrimaryContainer = Color(0xFF2C1600)
val md_theme_light_secondary = Color(0xFF7E5700)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDEAB)
val md_theme_light_onSecondaryContainer = Color(0xFF271900)
val md_theme_light_tertiary = Color(0xFF8E4E00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC1)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF626363)
val md_theme_light_onBackground = Color(0xFF002022)
val md_theme_light_surface = Color(0xFFF3FEFF)
val md_theme_light_onSurface = Color(0xFF002022)
val md_theme_light_surfaceVariant = Color(0xFFF2DFD0)
val md_theme_light_onSurfaceVariant = Color(0xFF50453A)
val md_theme_light_outline = Color(0xFF837568)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFFFFB86C)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF895100)
val md_theme_light_outlineVariant = Color(0xFFD5C3B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB86C)
val md_theme_dark_onPrimary = Color(0xFF492900)
val md_theme_dark_primaryContainer = Color(0xFF683C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBC)
val md_theme_dark_secondary = Color(0xFFFABC49)
val md_theme_dark_onSecondary = Color(0xFF422C00)
val md_theme_dark_secondaryContainer = Color(0xFF5F4100)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDEAB)
val md_theme_dark_tertiary = Color(0xFFFFB779)
val md_theme_dark_onTertiary = Color(0xFF4C2700)
val md_theme_dark_tertiaryContainer = Color(0xFF6C3A00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002022)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF50453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B5)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF002022)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFF895100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB86C)
val md_theme_dark_outlineVariant = Color(0xFF50453A)
val md_theme_dark_scrim = Color(0xFF000000)
